First draft of OpenAttestationEmbeddedRenderer
w3c-ccg/vc-render-method pull request #13
Opened 2024-06-07 04:00 UTC by HJunyuan

2024-06-11 19:15 UTC, msporny requested changes
A group of us discussed this on the VC API call today. 

General feedback was: the PR seems to be good enough to merge into the specification. The API section should probably go into the OAER section as a subsection. After that reformat is done we can merge this PR.

2024-06-11 19:28 UTC, TallTed requested changes

2024-06-11 19:28 UTC, TallTed commented on index.html
> +        verifiable credentials based on selected templates and must listen for
```suggestion
        verifiable credentials based on selected templates and needs to listen for
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +        There currently exists a number of OpenAttestationEmbeddedRenderer issuers
```suggestion
        There currently exist a number of OpenAttestationEmbeddedRenderer issuer
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +        When an <a>issuer</a> desires to specify an embedded rendering instructions
```suggestion
        When an <a>issuer</a> desires to specify embedded rendering instructions
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +          within an iframe specified by renderMethod.id. It MUST communicate with the
```suggestion
          within an `iframe` specified by `renderMethod`.`id`. It MUST communicate with the
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +          Host application using postMessage API to perform actions.
```suggestion
          Host application using `postMessage` API to perform actions.
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +                  document. The list of templates is returned from UPDATE_TEMPLATES
```suggestion
                  document. The list of templates is returned to `UPDATE_TEMPLATES`
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +                  list returned by GET_TEMPLATES. If not found, a default template is
```suggestion
                  list returned by `GET_TEMPLATES`. If not found, a default template is
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +                  MUST show the print dialog so the contents of the IFRAME can be
```suggestion
                  MUST show the print dialog so the contents of the iframe can be
```

2024-06-11 19:28 UTC, TallTed commented on index.html
> +                  RENDER_METHOD, or GET_TEMPLATES calls.
```suggestion
                  `RENDER_METHOD` or `GET_TEMPLATES` calls.
```

2024-06-18 02:23 UTC, cxcheng approved these changes
We have discussed and are ok.

2024-06-18 05:52 UTC, cxcheng commented
Updated with feedback from @msporny by moving the OpenAttestation Action API under the OpenAttestationEmbedderRenderer section.

2024-06-18 07:35 UTC, cxcheng commented
> A group of us discussed this on the VC API call today.
> 
> General feedback was: the PR seems to be good enough to merge into the specification. The API section should probably go into the OAER section as a subsection. After that reformat is done we can merge this PR.

Change requested by @msporny done

2024-06-18 14:04 UTC, msporny approved these changes

2024-06-18 14:04 UTC, merged